import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';
import fs from 'fs';
import path from 'path';

// ─── Détection automatique du framework ──────────────────────────────────────

type DetectedFramework = 'Flutter' | 'React (NextJS)' | 'Vue (Nuxt)' | 'React (Vite)' | 'Vue (Vite)' | 'Inconnu';

function detectFramework(cwd: string): DetectedFramework {
  const pubspec = path.join(cwd, 'pubspec.yaml');
  if (fs.existsSync(pubspec)) {
    return 'Flutter';
  }
  const pkgPath = path.join(cwd, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      if (deps['nuxt']) return 'Vue (Nuxt)';
      if (deps['next']) return 'React (NextJS)';
      if (deps['@vitejs/plugin-react'] || deps['react']) return 'React (Vite)';
      if (deps['@vitejs/plugin-vue'] || deps['vue']) return 'Vue (Vite)';
    } catch { /* ignore */ }
  }
  return 'Inconnu';
}

const WIDGET_FRAMEWORKS = [
  { name: '📱 Flutter', value: 'Flutter' },
  { name: '⚛️  React (NextJS)', value: 'React (NextJS)' },
  { name: '🟢 Vue (Nuxt)', value: 'Vue (Nuxt)' },
  { name: '⚛️  React (Vite)', value: 'React (Vite)' },
  { name: '🟢 Vue (Vite)', value: 'Vue (Vite)' },
];

const OPERATORS = [
  { name: 'MTN Côte d\'Ivoire (mtn_ci)', value: 'mtn_ci' },
  { name: 'MTN Bénin/Togo (mtn_open)', value: 'mtn_open' },
  { name: 'Moov Bénin (moov)', value: 'moov' },
  { name: 'Moov Togo (moov_tg)', value: 'moov_tg' },
  { name: 'Togocel', value: 'togocel' },
  { name: 'Free Sénégal (free_sn)', value: 'free_sn' },
  { name: 'Airtel Niger (airtel_ne)', value: 'airtel_ne' },
];

function generateBottomSheet(opts: {
  name: string;
  projectKey: string;
  operators: string[];
  primaryColor: string;
}): string {
  const operatorList = opts.operators.map((o) => `'${o}'`).join(', ');
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// ignore_for_file: library_private_types_in_public_api
import 'package:flutter/material.dart';
import 'package:feda_flutter/feda_flutter.dart';

/// Bottom sheet de paiement personnalisé
/// Projet : ${opts.name}
class ${toPascalCase(opts.name)}PaymentBottomSheet extends StatefulWidget {
  final double amount;
  final String description;
  final String currency;
  final VoidCallback? onSuccess;
  final VoidCallback? onFailure;

  const ${toPascalCase(opts.name)}PaymentBottomSheet({
    super.key,
    required this.amount,
    required this.description,
    this.currency = 'XOF',
    this.onSuccess,
    this.onFailure,
  });

  static Future<void> show(
    BuildContext context, {
    required double amount,
    required String description,
    VoidCallback? onSuccess,
    VoidCallback? onFailure,
  }) {
    return showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => ${toPascalCase(opts.name)}PaymentBottomSheet(
        amount: amount,
        description: description,
        onSuccess: onSuccess,
        onFailure: onFailure,
      ),
    );
  }

  @override
  _${toPascalCase(opts.name)}PaymentBottomSheetState createState() => _${toPascalCase(opts.name)}PaymentBottomSheetState();
}

class _${toPascalCase(opts.name)}PaymentBottomSheetState extends State<${toPascalCase(opts.name)}PaymentBottomSheet> {
  String? _selectedOperator;
  final _phoneController = TextEditingController();
  bool _isLoading = false;

  static const _primaryColor = Color(0xFF${opts.primaryColor.replace('#', '')});
  static const _supportedOperators = [${operatorList}];

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      padding: EdgeInsets.fromLTRB(24, 16, 24, MediaQuery.of(context).viewInsets.bottom + 24),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Handle bar
          Center(child: Container(width: 40, height: 4, decoration: BoxDecoration(
            color: Colors.grey[300], borderRadius: BorderRadius.circular(2)))),
          const SizedBox(height: 16),
          Text(widget.description, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          Text('\${widget.amount.toStringAsFixed(0)} \${widget.currency}',
              style: TextStyle(color: _primaryColor, fontSize: 22, fontWeight: FontWeight.bold)),
          const SizedBox(height: 20),
          // Opérateur
          DropdownButtonFormField<String>(
            decoration: InputDecoration(labelText: 'Opérateur mobile', border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12))),
            items: _supportedOperators.map((op) =>
              DropdownMenuItem(value: op, child: Text(op))).toList(),
            onChanged: (v) => setState(() => _selectedOperator = v),
          ),
          const SizedBox(height: 12),
          // Téléphone
          TextField(
            controller: _phoneController,
            keyboardType: TextInputType.phone,
            decoration: InputDecoration(
              labelText: 'Numéro de téléphone (ex: +229...)',
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
              prefixIcon: const Icon(Icons.phone),
            ),
          ),
          const SizedBox(height: 20),
          // Bouton paiement
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: _isLoading ? null : _pay,
              style: ElevatedButton.styleFrom(
                backgroundColor: _primaryColor,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              child: _isLoading
                  ? const CircularProgressIndicator(color: Colors.white, strokeWidth: 2)
                  : Text('Payer \${widget.amount.toStringAsFixed(0)} \${widget.currency}',
                      style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _pay() async {
    final phone = _phoneController.text.trim();
    if (_selectedOperator == null || phone.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Veuillez sélectionner un opérateur et saisir votre numéro.')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      // Étape 1 : Créer la transaction
      final txResp = await FedaFlutter.instance.transactions.createTransaction(
        TransactionCreate(
          description: widget.description,
          amount: widget.amount,
          currency: CurrencyIso(iso: widget.currency),
        ),
      );
      final tx = txResp.data;
      if (tx == null) throw Exception('Impossible de créer la transaction.');

      // Étape 2 : Récupérer le token de paiement
      final tokenResp = await FedaFlutter.instance.transactions.getTransactionToken(tx.id);
      final tokenData = tokenResp.data;
      if (tokenData == null) throw Exception('Impossible de récupérer le token de paiement.');

      // Étape 3 : Déclencher le paiement direct (mobile money)
      await FedaFlutter.instance.transactions.directPayment(
        TransactionDirectPayment(
          currency: CurrencyIso(iso: widget.currency),
          description: widget.description,
          amount: widget.amount,
          token: tokenData.token,
          phoneNumber: PhoneNumber(number: phone, country: _countryFromOperator(_selectedOperator!)),
        ),
        mode: _selectedOperator!,
      );

      widget.onSuccess?.call();
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Paiement initié avec succès ! Validez sur votre téléphone.'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      widget.onFailure?.call();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Échec du paiement : \${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  /// Retourne le code pays ISO à 2 lettres selon l'opérateur sélectionné.
  String _countryFromOperator(String operator) {
    switch (operator) {
      case 'mtn_ci': return 'CI';
      case 'mtn_open': return 'BJ';
      case 'moov': return 'BJ';
      case 'moov_tg': return 'TG';
      case 'togocel': return 'TG';
      case 'free_sn': return 'SN';
      case 'airtel_ne': return 'NE';
      default: return 'BJ';
    }
  }

  @override
  void dispose() {
    _phoneController.dispose();
    super.dispose();
  }
}

String _toPascalCase(String s) => s.split('-').map((w) => w[0].toUpperCase() + w.substring(1)).join();
`;
}

function generatePayButton(opts: {
  name: string;
  projectKey: string;
  operators: string[];
  primaryColor: string;
}): string {
  const className = toPascalCase(opts.name);
  const operatorList = opts.operators.map((o) => `'${o}'`).join(', ');
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// ignore_for_file: library_private_types_in_public_api
import 'package:flutter/material.dart';
import 'package:feda_flutter/feda_flutter.dart';

/// Bouton de paiement inline
/// Projet : ${opts.name}
class ${className}PayButton extends StatefulWidget {
  final double amount;
  final String description;
  final String currency;
  final String phoneNumber;
  final String operator;
  final VoidCallback? onSuccess;
  final VoidCallback? onFailure;
  final String label;

  const ${className}PayButton({
    super.key,
    required this.amount,
    required this.description,
    required this.phoneNumber,
    required this.operator,
    this.currency = 'XOF',
    this.onSuccess,
    this.onFailure,
    this.label = 'Payer',
  });

  @override
  _${className}PayButtonState createState() => _${className}PayButtonState();
}

class _${className}PayButtonState extends State<${className}PayButton> {
  bool _isLoading = false;
  static const _primaryColor = Color(0xFF${opts.primaryColor.replace('#', '')});
  static const _supportedOperators = [${operatorList}];

  Future<void> _pay() async {
    if (!_supportedOperators.contains(widget.operator)) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Opérateur non supporté : \${widget.operator}')),
      );
      return;
    }
    setState(() => _isLoading = true);
    try {
      final txResp = await FedaFlutter.instance.transactions.createTransaction(
        TransactionCreate(
          description: widget.description,
          amount: widget.amount,
          currency: CurrencyIso(iso: widget.currency),
        ),
      );
      final tx = txResp.data;
      if (tx == null) throw Exception('Impossible de créer la transaction.');

      final tokenResp = await FedaFlutter.instance.transactions.getTransactionToken(tx.id);
      final tokenData = tokenResp.data;
      if (tokenData == null) throw Exception('Impossible de récupérer le token.');

      await FedaFlutter.instance.transactions.directPayment(
        TransactionDirectPayment(
          currency: CurrencyIso(iso: widget.currency),
          description: widget.description,
          amount: widget.amount,
          token: tokenData.token,
          phoneNumber: PhoneNumber(number: widget.phoneNumber, country: _countryFromOperator(widget.operator)),
        ),
        mode: widget.operator,
      );

      widget.onSuccess?.call();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Paiement initié ! Validez sur votre téléphone.'), backgroundColor: Colors.green),
        );
      }
    } catch (e) {
      widget.onFailure?.call();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erreur : \${e.toString()}'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  String _countryFromOperator(String op) {
    const map = {
      'mtn_ci': 'CI', 'mtn_open': 'BJ', 'moov': 'BJ',
      'moov_tg': 'TG', 'togocel': 'TG', 'free_sn': 'SN', 'airtel_ne': 'NE',
    };
    return map[op] ?? 'BJ';
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.infinity,
      child: ElevatedButton(
        onPressed: _isLoading ? null : _pay,
        style: ElevatedButton.styleFrom(
          backgroundColor: _primaryColor,
          padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 24),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        ),
        child: _isLoading
            ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
            : Text('\${widget.label} \${widget.amount.toStringAsFixed(0)} \${widget.currency}',
                style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
      ),
    );
  }
}
`;
}

function generateVuePaymentWidget(opts: { name: string; projectKey: string; cssFramework: string }): string {
  const className = toPascalCase(opts.name);
  const useTailwind = opts.cssFramework === 'tailwind';
  return `<!-- Generated by wallet-cli — ${new Date().toISOString()} -->
<!-- Widget de paiement FedaPay — Vue/Nuxt -->
<script setup lang="ts">
import { ref } from 'vue'

interface Props {
  amount: number
  description: string
  currency?: string
  onSuccess?: () => void
  onFailure?: (err: Error) => void
}

const props = withDefaults(defineProps<Props>(), { currency: 'XOF' })

const CLOUD_URL = import.meta.env.NUXT_PUBLIC_FEDA_CLOUD_URL ?? import.meta.env.VITE_FEDA_CLOUD_URL ?? ''
const PROJECT_KEY = import.meta.env.NUXT_PUBLIC_FEDA_PROJECT_KEY ?? import.meta.env.VITE_FEDA_PROJECT_KEY ?? '${opts.projectKey}'

const OPERATORS = [
  { label: 'MTN Bénin / Togo', value: 'mtn_open' },
  { label: 'Moov Bénin', value: 'moov' },
  { label: 'Moov Togo', value: 'moov_tg' },
  { label: 'Togocel', value: 'togocel' },
  { label: 'MTN Côte d\\'Ivoire', value: 'mtn_ci' },
  { label: 'Free Sénégal', value: 'free_sn' },
]

const selectedOperator = ref(OPERATORS[0].value)
const phone = ref('')
const isLoading = ref(false)
const error = ref<string | null>(null)
const success = ref(false)

async function pay() {
  if (!phone.value) { error.value = 'Veuillez saisir un numéro de téléphone.'; return }
  isLoading.value = true; error.value = null

  try {
    const headers = {
      'Content-Type': 'application/json',
      'x-feda-project-key': PROJECT_KEY,
    }

    // Étape 1 — Créer la transaction
    const txRes = await fetch(\`\${CLOUD_URL}/fedapay/transactions\`, {
      method: 'POST', headers,
      body: JSON.stringify({ description: props.description, amount: props.amount, currency: { iso: props.currency } }),
    })
    if (!txRes.ok) throw new Error(await txRes.text())
    const { transaction } = await txRes.json()

    // Étape 2 — Récupérer le token
    const tokenRes = await fetch(\`\${CLOUD_URL}/fedapay/transactions/\${transaction.id}/token\`, { headers })
    if (!tokenRes.ok) throw new Error(await tokenRes.text())
    const { token } = await tokenRes.json()

    // Étape 3 — Paiement direct
    const payRes = await fetch(\`\${CLOUD_URL}/fedapay/transactions?mode=\${selectedOperator.value}\`, {
      method: 'POST', headers,
      body: JSON.stringify({
        currency: { iso: props.currency }, description: props.description,
        amount: props.amount, token,
        phone_number: { number: phone.value, country: countryFromOperator(selectedOperator.value) },
      }),
    })
    if (!payRes.ok) throw new Error(await payRes.text())

    success.value = true
    props.onSuccess?.()
  } catch (e: any) {
    error.value = e.message ?? 'Erreur inconnue'
    props.onFailure?.(e)
  } finally {
    isLoading.value = false
  }
}

function countryFromOperator(op: string): string {
  const map: Record<string, string> = {
    mtn_ci: 'CI', mtn_open: 'BJ', moov: 'BJ', moov_tg: 'TG', togocel: 'TG', free_sn: 'SN', airtel_ne: 'NE',
  }
  return map[op] ?? 'BJ'
}
</script>

<template>
  <div${useTailwind ? ' class="bg-white rounded-2xl shadow-lg p-6 max-w-sm mx-auto"' : ''}>
    <div v-if="success"${useTailwind ? ' class="text-center py-8"' : ''}>
      <p${useTailwind ? ' class="text-green-600 text-lg font-semibold"' : ''}>✅ Paiement initié avec succès !</p>
      <p${useTailwind ? ' class="text-gray-500 text-sm mt-2"' : ''}>Validez le paiement sur votre téléphone.</p>
    </div>
    <template v-else>
      <h3${useTailwind ? ' class="text-lg font-bold mb-1"' : ''}>{{ description }}</h3>
      <p${useTailwind ? ' class="text-2xl font-bold text-blue-600 mb-6"' : ''}>{{ amount.toLocaleString() }} {{ currency }}</p>

      <div${useTailwind ? ' class="mb-4"' : ''}>
        <label${useTailwind ? ' class="block text-sm font-medium text-gray-700 mb-1"' : ''}>Opérateur</label>
        <select v-model="selectedOperator"${useTailwind ? ' class="w-full border rounded-lg px-3 py-2"' : ''}>
          <option v-for="op in OPERATORS" :key="op.value" :value="op.value">{{ op.label }}</option>
        </select>
      </div>

      <div${useTailwind ? ' class="mb-4"' : ''}>
        <label${useTailwind ? ' class="block text-sm font-medium text-gray-700 mb-1"' : ''}>Numéro de téléphone</label>
        <input
          v-model="phone" type="tel" placeholder="+229 60 00 00 00"
          ${useTailwind ? 'class="w-full border rounded-lg px-3 py-2"' : ''}
        />
      </div>

      <p v-if="error"${useTailwind ? ' class="text-red-500 text-sm mb-3"' : ''}>{{ error }}</p>

      <button
        :disabled="isLoading"
        @click="pay"
        ${useTailwind ? 'class="w-full bg-blue-600 text-white font-semibold py-3 rounded-xl disabled:opacity-50 hover:bg-blue-700 transition"' : ''}
      >
        <span v-if="isLoading">Traitement en cours…</span>
        <span v-else>Payer {{ amount.toLocaleString() }} {{ currency }}</span>
      </button>
    </template>
  </div>
</template>
`;
}

function generateReactPaymentWidget(opts: { name: string; projectKey: string; cssFramework: string }): string {
  const className = toPascalCase(opts.name);
  const useTailwind = opts.cssFramework === 'tailwind';
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// Widget de paiement FedaPay — React
'use client';
import { useState } from 'react';

const CLOUD_URL = process.env.NEXT_PUBLIC_FEDA_CLOUD_URL ?? process.env.VITE_FEDA_CLOUD_URL ?? '';
const PROJECT_KEY = process.env.NEXT_PUBLIC_FEDA_PROJECT_KEY ?? process.env.VITE_FEDA_PROJECT_KEY ?? '${opts.projectKey}';

const OPERATORS = [
  { label: 'MTN Bénin / Togo', value: 'mtn_open' },
  { label: 'Moov Bénin', value: 'moov' },
  { label: 'Moov Togo', value: 'moov_tg' },
  { label: 'Togocel', value: 'togocel' },
  { label: "MTN Côte d'Ivoire", value: 'mtn_ci' },
  { label: 'Free Sénégal', value: 'free_sn' },
];

interface Props {
  amount: number;
  description: string;
  currency?: string;
  onSuccess?: () => void;
  onFailure?: (err: Error) => void;
}

function countryFromOperator(op: string): string {
  const map: Record<string, string> = {
    mtn_ci: 'CI', mtn_open: 'BJ', moov: 'BJ', moov_tg: 'TG', togocel: 'TG', free_sn: 'SN', airtel_ne: 'NE',
  };
  return map[op] ?? 'BJ';
}

export function ${className}PaymentWidget({ amount, description, currency = 'XOF', onSuccess, onFailure }: Props) {
  const [operator, setOperator] = useState(OPERATORS[0].value);
  const [phone, setPhone] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const pay = async () => {
    if (!phone) { setError('Veuillez saisir un numéro de téléphone.'); return; }
    setIsLoading(true); setError(null);

    const headers = { 'Content-Type': 'application/json', 'x-feda-project-key': PROJECT_KEY };

    try {
      // Étape 1 — Créer la transaction
      const txRes = await fetch(\`\${CLOUD_URL}/fedapay/transactions\`, {
        method: 'POST', headers,
        body: JSON.stringify({ description, amount, currency: { iso: currency } }),
      });
      if (!txRes.ok) throw new Error(await txRes.text());
      const { transaction } = await txRes.json();

      // Étape 2 — Récupérer le token
      const tokenRes = await fetch(\`\${CLOUD_URL}/fedapay/transactions/\${transaction.id}/token\`, { headers });
      if (!tokenRes.ok) throw new Error(await tokenRes.text());
      const { token } = await tokenRes.json();

      // Étape 3 — Paiement direct
      const payRes = await fetch(\`\${CLOUD_URL}/fedapay/transactions?mode=\${operator}\`, {
        method: 'POST', headers,
        body: JSON.stringify({
          currency: { iso: currency }, description, amount, token,
          phone_number: { number: phone, country: countryFromOperator(operator) },
        }),
      });
      if (!payRes.ok) throw new Error(await payRes.text());

      setSuccess(true);
      onSuccess?.();
    } catch (e: any) {
      setError(e.message ?? 'Erreur inconnue');
      onFailure?.(e);
    } finally {
      setIsLoading(false);
    }
  };

  if (success) {
    return (
      <div${useTailwind ? ' className="text-center py-8"' : ''}>
        <p${useTailwind ? ' className="text-green-600 text-lg font-semibold"' : ''}>✅ Paiement initié avec succès !</p>
        <p${useTailwind ? ' className="text-gray-500 text-sm mt-2"' : ''}>Validez le paiement sur votre téléphone.</p>
      </div>
    );
  }

  return (
    <div${useTailwind ? ' className="bg-white rounded-2xl shadow-lg p-6 max-w-sm mx-auto"' : ''}>
      <h3${useTailwind ? ' className="text-lg font-bold mb-1"' : ''}>{description}</h3>
      <p${useTailwind ? ' className="text-2xl font-bold text-blue-600 mb-6"' : ''}>{amount.toLocaleString()} {currency}</p>

      <div${useTailwind ? ' className="mb-4"' : ''}>
        <label${useTailwind ? ' className="block text-sm font-medium text-gray-700 mb-1"' : ''}>Opérateur</label>
        <select value={operator} onChange={(e) => setOperator(e.target.value)}${useTailwind ? ' className="w-full border rounded-lg px-3 py-2"' : ''}>
          {OPERATORS.map((op) => <option key={op.value} value={op.value}>{op.label}</option>)}
        </select>
      </div>

      <div${useTailwind ? ' className="mb-4"' : ''}>
        <label${useTailwind ? ' className="block text-sm font-medium text-gray-700 mb-1"' : ''}>Numéro de téléphone</label>
        <input
          type="tel" value={phone} onChange={(e) => setPhone(e.target.value)}
          placeholder="+229 60 00 00 00"
          ${useTailwind ? 'className="w-full border rounded-lg px-3 py-2"' : ''}
        />
      </div>

      {error && <p${useTailwind ? ' className="text-red-500 text-sm mb-3"' : ''}>{error}</p>}

      <button
        onClick={pay} disabled={isLoading}
        ${useTailwind ? 'className="w-full bg-blue-600 text-white font-semibold py-3 rounded-xl disabled:opacity-50 hover:bg-blue-700 transition"' : ''}
      >
        {isLoading ? 'Traitement en cours…' : \`Payer \${amount.toLocaleString()} \${currency}\`}
      </button>
    </div>
  );
}
`;
}

function generateFlutterPricingPage(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// ignore_for_file: library_private_types_in_public_api
import 'package:flutter/material.dart';

/// Modèle de plan — adapté depuis GET /billing/plans
class BillingPlan {
  final String id;
  final String name;
  final num amount;
  final String currency;
  final String interval; // monthly, yearly
  final int? trialDays;

  BillingPlan({required this.id, required this.name, required this.amount,
    required this.currency, required this.interval, this.trialDays});

  factory BillingPlan.fromJson(Map<String, dynamic> j) => BillingPlan(
    id: j['_id'] ?? '', name: j['name'] ?? '',
    amount: j['amount'] ?? 0, currency: j['currency'] ?? 'XOF',
    interval: j['interval'] ?? 'monthly', trialDays: j['trialDays'],
  );
}

class PricingPage extends StatefulWidget {
  final String cloudUrl;
  final String projectKey;
  final String userId;
  final VoidCallback? onSubscribed;

  const PricingPage({
    super.key,
    required this.cloudUrl,
    required this.projectKey,
    required this.userId,
    this.onSubscribed,
  });

  @override
  _PricingPageState createState() => _PricingPageState();
}

class _PricingPageState extends State<PricingPage> {
  List<BillingPlan> _plans = [];
  bool _loading = true;
  String? _subscribing;

  @override
  void initState() {
    super.initState();
    _fetchPlans();
  }

  Future<void> _fetchPlans() async {
    try {
      // Remplacez par votre client HTTP (Dio, http, etc.)
      // final resp = await Dio().get(
      //   '\${widget.cloudUrl}/billing/plans',
      //   options: Options(headers: {'x-feda-project-key': widget.projectKey}),
      // );
      // setState(() => _plans = (resp.data as List).map((e) => BillingPlan.fromJson(e)).toList());
      setState(() => _loading = false);
    } catch (_) {
      setState(() => _loading = false);
    }
  }

  Future<void> _subscribe(BillingPlan plan) async {
    setState(() => _subscribing = plan.id);
    try {
      // POST \${widget.cloudUrl}/billing/subscriptions
      // body: { planId: plan.id, userId: widget.userId }
      widget.onSubscribed?.call();
    } catch (_) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Erreur lors de la souscription'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _subscribing = null);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Nos offres')),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _plans.isEmpty
              ? const Center(child: Text('Aucun plan disponible'))
              : ListView.builder(
                  padding: const EdgeInsets.all(16),
                  itemCount: _plans.length,
                  itemBuilder: (_, i) {
                    final plan = _plans[i];
                    return Card(
                      margin: const EdgeInsets.only(bottom: 16),
                      child: Padding(
                        padding: const EdgeInsets.all(20),
                        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                          Text(plan.name, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                          const SizedBox(height: 8),
                          Text('\${plan.amount.toStringAsFixed(0)} \${plan.currency} / \${plan.interval}',
                              style: const TextStyle(fontSize: 18, color: Colors.blue)),
                          if (plan.trialDays != null) ...[
                            const SizedBox(height: 4),
                            Text('\${plan.trialDays} jours d\\'essai gratuit',
                                style: const TextStyle(color: Colors.green)),
                          ],
                          const SizedBox(height: 16),
                          SizedBox(
                            width: double.infinity,
                            child: ElevatedButton(
                              onPressed: _subscribing != null ? null : () => _subscribe(plan),
                              child: _subscribing == plan.id
                                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                                  : const Text('Souscrire'),
                            ),
                          ),
                        ]),
                      ),
                    );
                  },
                ),
    );
  }
}
`;
}

function generateNuxtPricingPage(): string {
  return `<!-- Generated by wallet-cli — ${new Date().toISOString()} -->
<script setup lang="ts">
interface Plan {
  _id: string
  name: string
  amount: number
  currency: string
  interval: string
  trialDays?: number
}

const props = defineProps<{ projectKey: string; cloudUrl: string; userId: string }>()
const emit = defineEmits<{ (e: 'subscribed', planId: string): void }>()

const { data: plans, pending } = await useFetch<Plan[]>(\`\${props.cloudUrl}/billing/plans\`, {
  headers: { 'x-feda-project-key': props.projectKey },
})

const subscribing = ref<string | null>(null)

async function subscribe(plan: Plan) {
  subscribing.value = plan._id
  try {
    await $fetch(\`\${props.cloudUrl}/billing/subscriptions\`, {
      method: 'POST',
      headers: { 'x-feda-project-key': props.projectKey },
      body: { planId: plan._id, userId: props.userId },
    })
    emit('subscribed', plan._id)
  } catch (e: any) {
    console.error('Erreur souscription', e)
  } finally {
    subscribing.value = null
  }
}
</script>

<template>
  <div class="pricing-page">
    <h2 class="text-2xl font-bold text-center mb-8">Nos offres</h2>
    <div v-if="pending" class="flex justify-center">
      <UIcon name="i-heroicons-arrow-path" class="animate-spin text-4xl" />
    </div>
    <div v-else class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <UCard v-for="plan in plans" :key="plan._id" class="flex flex-col">
        <template #header>
          <h3 class="text-xl font-semibold">{{ plan.name }}</h3>
        </template>
        <div class="flex-1">
          <p class="text-3xl font-bold text-primary">
            {{ plan.amount.toLocaleString() }} {{ plan.currency }}
            <span class="text-sm font-normal text-gray-500">/ {{ plan.interval }}</span>
          </p>
          <p v-if="plan.trialDays" class="mt-2 text-sm text-green-600">
            {{ plan.trialDays }} jours d'essai gratuit
          </p>
        </div>
        <template #footer>
          <UButton
            block
            :loading="subscribing === plan._id"
            :disabled="subscribing !== null"
            @click="subscribe(plan)"
          >
            Souscrire
          </UButton>
        </template>
      </UCard>
    </div>
  </div>
</template>
`;
}

function generateNextPricingPage(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
'use client';
import { useEffect, useState } from 'react';

interface Plan {
  _id: string;
  name: string;
  amount: number;
  currency: string;
  interval: string;
  trialDays?: number;
}

interface Props {
  projectKey: string;
  cloudUrl: string;
  userId: string;
  onSubscribed?: (planId: string) => void;
}

export function PricingPage({ projectKey, cloudUrl, userId, onSubscribed }: Props) {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [loading, setLoading] = useState(true);
  const [subscribing, setSubscribing] = useState<string | null>(null);

  useEffect(() => {
    fetch(\`\${cloudUrl}/billing/plans\`, {
      headers: { 'x-feda-project-key': projectKey },
    })
      .then((r) => r.json())
      .then(setPlans)
      .finally(() => setLoading(false));
  }, [cloudUrl, projectKey]);

  const subscribe = async (plan: Plan) => {
    setSubscribing(plan._id);
    try {
      await fetch(\`\${cloudUrl}/billing/subscriptions\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-feda-project-key': projectKey },
        body: JSON.stringify({ planId: plan._id, userId }),
      });
      onSubscribed?.(plan._id);
    } finally {
      setSubscribing(null);
    }
  };

  if (loading) return <div className="text-center py-16">Chargement...</div>;

  return (
    <div className="pricing-page max-w-4xl mx-auto py-12 px-4">
      <h2 className="text-3xl font-bold text-center mb-10">Nos offres</h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {plans.map((plan) => (
          <div key={plan._id} className="border rounded-xl p-6 flex flex-col shadow-sm">
            <h3 className="text-xl font-semibold mb-2">{plan.name}</h3>
            <p className="text-3xl font-bold text-blue-600 mb-1">
              {plan.amount.toLocaleString()} {plan.currency}
              <span className="text-sm font-normal text-gray-400"> / {plan.interval}</span>
            </p>
            {plan.trialDays && (
              <p className="text-sm text-green-600 mb-4">{plan.trialDays} jours gratuits</p>
            )}
            <button
              className="mt-auto bg-blue-600 text-white rounded-lg py-2 px-4 disabled:opacity-50"
              disabled={subscribing !== null}
              onClick={() => subscribe(plan)}
            >
              {subscribing === plan._id ? 'En cours...' : 'Souscrire'}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
`;
}

function generateFlutterCustomerPortal(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// ignore_for_file: library_private_types_in_public_api
import 'package:flutter/material.dart';

/// Portail client — affiche les abonnements actifs et l'historique
class CustomerPortal extends StatefulWidget {
  final String cloudUrl;
  final String projectKey;
  final String userId;

  const CustomerPortal({
    super.key,
    required this.cloudUrl,
    required this.projectKey,
    required this.userId,
  });

  @override
  _CustomerPortalState createState() => _CustomerPortalState();
}

class _CustomerPortalState extends State<CustomerPortal> {
  List<Map<String, dynamic>> _subscriptions = [];
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _fetchSubscriptions();
  }

  Future<void> _fetchSubscriptions() async {
    try {
      // GET \${widget.cloudUrl}/billing/subscriptions?userId=\${widget.userId}
      // headers: { 'x-feda-project-key': widget.projectKey }
      setState(() => _loading = false);
    } catch (_) {
      setState(() => _loading = false);
    }
  }

  Future<void> _cancel(String subscriptionId) async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (_) => AlertDialog(
        title: const Text('Annuler l\\'abonnement'),
        content: const Text('Êtes-vous sûr de vouloir annuler cet abonnement ?'),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Non')),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Oui, annuler'),
          ),
        ],
      ),
    );
    if (confirm != true) return;
    // DELETE \${widget.cloudUrl}/billing/subscriptions/\$subscriptionId
    setState(() => _subscriptions.removeWhere((s) => s['_id'] == subscriptionId));
  }

  Color _statusColor(String status) {
    switch (status) {
      case 'active': return Colors.green;
      case 'trialing': return Colors.blue;
      case 'past_due': return Colors.orange;
      case 'expired': case 'canceled': return Colors.red;
      default: return Colors.grey;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Mes abonnements')),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _subscriptions.isEmpty
              ? const Center(child: Text('Aucun abonnement actif'))
              : ListView.builder(
                  padding: const EdgeInsets.all(16),
                  itemCount: _subscriptions.length,
                  itemBuilder: (_, i) {
                    final sub = _subscriptions[i];
                    return Card(
                      child: ListTile(
                        title: Text(sub['planName'] ?? 'Plan inconnu'),
                        subtitle: Text('Expire le \${sub['currentPeriodEnd'] ?? 'N/A'}'),
                        trailing: Row(mainAxisSize: MainAxisSize.min, children: [
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                            decoration: BoxDecoration(
                              color: _statusColor(sub['status'] ?? '').withOpacity(0.1),
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: Text(sub['status'] ?? '',
                                style: TextStyle(color: _statusColor(sub['status'] ?? ''), fontSize: 12)),
                          ),
                          const SizedBox(width: 8),
                          if (sub['status'] == 'active' || sub['status'] == 'trialing')
                            IconButton(
                              icon: const Icon(Icons.cancel_outlined, color: Colors.red),
                              onPressed: () => _cancel(sub['_id']),
                            ),
                        ]),
                      ),
                    );
                  },
                ),
    );
  }
}
`;
}

function generateNuxtCustomerPortal(): string {
  return `<!-- Generated by wallet-cli — ${new Date().toISOString()} -->
<script setup lang="ts">
interface Subscription {
  _id: string
  planName: string
  status: 'active' | 'trialing' | 'past_due' | 'expired' | 'canceled'
  currentPeriodStart: string
  currentPeriodEnd: string
  amount: number
  currency: string
}

const props = defineProps<{ projectKey: string; cloudUrl: string; userId: string }>()

const { data: subscriptions, refresh } = await useFetch<Subscription[]>(
  \`\${props.cloudUrl}/billing/subscriptions\`,
  { headers: { 'x-feda-project-key': props.projectKey }, query: { userId: props.userId } }
)

const statusColor = (status: string) => ({
  active: 'success', trialing: 'info', past_due: 'warning',
  expired: 'error', canceled: 'neutral',
}[status] || 'neutral')

async function cancel(id: string) {
  await $fetch(\`\${props.cloudUrl}/billing/subscriptions/\${id}\`, {
    method: 'DELETE',
    headers: { 'x-feda-project-key': props.projectKey },
  })
  await refresh()
}
</script>

<template>
  <div class="customer-portal">
    <h2 class="text-2xl font-bold mb-6">Mes abonnements</h2>
    <div v-if="!subscriptions?.length" class="text-center py-12 text-gray-500">
      Aucun abonnement actif.
    </div>
    <UTable
      v-else
      :rows="subscriptions"
      :columns="[
        { key: 'planName', label: 'Plan' },
        { key: 'status', label: 'Statut' },
        { key: 'currentPeriodEnd', label: 'Expire le' },
        { key: 'amount', label: 'Montant' },
        { key: 'actions', label: '' },
      ]"
    >
      <template #status-data="{ row }">
        <UBadge :color="statusColor(row.status)" variant="subtle">{{ row.status }}</UBadge>
      </template>
      <template #amount-data="{ row }">
        {{ row.amount.toLocaleString() }} {{ row.currency }}
      </template>
      <template #currentPeriodEnd-data="{ row }">
        {{ new Date(row.currentPeriodEnd).toLocaleDateString('fr-FR') }}
      </template>
      <template #actions-data="{ row }">
        <UButton
          v-if="['active','trialing'].includes(row.status)"
          color="error"
          variant="ghost"
          size="sm"
          icon="i-heroicons-x-circle"
          @click="cancel(row._id)"
        >
          Annuler
        </UButton>
      </template>
    </UTable>
  </div>
</template>
`;
}

function generateNextCustomerPortal(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
'use client';
import { useEffect, useState } from 'react';

interface Subscription {
  _id: string;
  planName: string;
  status: 'active' | 'trialing' | 'past_due' | 'expired' | 'canceled';
  currentPeriodEnd: string;
  amount: number;
  currency: string;
}

interface Props { projectKey: string; cloudUrl: string; userId: string; }

const STATUS_COLOR: Record<string, string> = {
  active: 'bg-green-100 text-green-700',
  trialing: 'bg-blue-100 text-blue-700',
  past_due: 'bg-orange-100 text-orange-700',
  expired: 'bg-red-100 text-red-700',
  canceled: 'bg-gray-100 text-gray-500',
};

export function CustomerPortal({ projectKey, cloudUrl, userId }: Props) {
  const [subs, setSubs] = useState<Subscription[]>([]);
  const [loading, setLoading] = useState(true);

  const load = () =>
    fetch(\`\${cloudUrl}/billing/subscriptions?userId=\${userId}\`, {
      headers: { 'x-feda-project-key': projectKey },
    }).then((r) => r.json()).then(setSubs).finally(() => setLoading(false));

  useEffect(() => { load(); }, []);

  const cancel = async (id: string) => {
    await fetch(\`\${cloudUrl}/billing/subscriptions/\${id}\`, {
      method: 'DELETE', headers: { 'x-feda-project-key': projectKey },
    });
    load();
  };

  if (loading) return <div className="text-center py-12">Chargement...</div>;

  return (
    <div className="customer-portal max-w-3xl mx-auto py-8">
      <h2 className="text-2xl font-bold mb-6">Mes abonnements</h2>
      {subs.length === 0 ? (
        <p className="text-gray-500 text-center">Aucun abonnement actif.</p>
      ) : (
        <table className="w-full border-collapse">
          <thead>
            <tr className="text-left border-b">
              <th className="py-2">Plan</th><th>Statut</th><th>Expire le</th><th>Montant</th><th></th>
            </tr>
          </thead>
          <tbody>
            {subs.map((s) => (
              <tr key={s._id} className="border-b">
                <td className="py-3">{s.planName}</td>
                <td><span className={\`px-2 py-1 rounded-full text-xs \${STATUS_COLOR[s.status]}\`}>{s.status}</span></td>
                <td>{new Date(s.currentPeriodEnd).toLocaleDateString('fr-FR')}</td>
                <td>{s.amount.toLocaleString()} {s.currency}</td>
                <td>
                  {['active','trialing'].includes(s.status) && (
                    <button className="text-red-500 text-sm hover:underline" onClick={() => cancel(s._id)}>
                      Annuler
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
`;
}

function generateFlutterGuard(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// Guard GoRouter — Vérification abonnement SaaS
// Nécessite le package go_router dans pubspec.yaml
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// Service d'abonnement — adaptez à votre implémentation
abstract class SubscriptionService {
  static bool isActive = false; // Remplacez par un appel réel à votre API
}

/// Redirect utilisé dans GoRouter pour protéger les routes payantes.
///
/// Exemple d'utilisation dans votre GoRouter :
/// \`\`\`dart
/// GoRouter(
///   redirect: saasGuardRedirect,
///   routes: [
///     GoRoute(path: '/dashboard', builder: (_, __) => DashboardPage()),
///     GoRoute(path: '/subscribe', builder: (_, __) => SubscribePage()),
///   ],
/// )
/// \`\`\`
String? saasGuardRedirect(BuildContext context, GoRouterState state) {
  const protectedRoutes = ['/dashboard', '/profile', '/premium'];
  final isProtected = protectedRoutes.any((r) => state.matchedLocation.startsWith(r));

  if (isProtected && !SubscriptionService.isActive) {
    return '/subscribe?from=\${state.matchedLocation}';
  }
  return null;
}

/// Widget wrapper qui bloque l'accès si l'abonnement est inactif.
class SaasGate extends StatelessWidget {
  final Widget child;
  final Widget? fallback;

  const SaasGate({super.key, required this.child, this.fallback});

  @override
  Widget build(BuildContext context) {
    if (!SubscriptionService.isActive) {
      return fallback ??
          Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.lock_outline, size: 64, color: Colors.grey),
                  const SizedBox(height: 16),
                  const Text('Abonnement requis', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  const Text('Cette fonctionnalité nécessite un abonnement actif.'),
                  const SizedBox(height: 24),
                  ElevatedButton(
                    onPressed: () => GoRouter.of(context).go('/subscribe'),
                    child: const Text('Voir les offres'),
                  ),
                ],
              ),
            ),
          );
    }
    return child;
  }
}
`;
}

function generateNestJsGuard(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// Guard NestJS — Vérification abonnement SaaS
import { Injectable, CanActivate, ExecutionContext, ForbiddenException } from '@nestjs/common';
import { Reflector } from '@nestjs/core';

export const PUBLIC_KEY = 'isPublic';
export const Public = () => require('@nestjs/common').SetMetadata(PUBLIC_KEY, true);

/**
 * Guard NestJS qui vérifie si l'utilisateur a un abonnement SaaS actif.
 *
 * Utilisation :
 * \`\`\`typescript
 * // Dans app.module.ts (guard global)
 * providers: [{ provide: APP_GUARD, useClass: SaasSubscriptionGuard }]
 *
 * // Sur une route publique
 * @Public()
 * @Get('health')
 * healthCheck() { return 'ok'; }
 * \`\`\`
 *
 * Adaptez \`SaasService\` à votre implémentation réelle.
 */
@Injectable()
export class SaasSubscriptionGuard implements CanActivate {
  constructor(private readonly reflector: Reflector) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    // Routes marquées @Public() sont exclues
    const isPublic = this.reflector.getAllAndOverride<boolean>(PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);
    if (isPublic) return true;

    const request = context.switchToHttp().getRequest();
    const user = request.user; // Injecté par JwtAuthGuard en amont

    if (!user) {
      throw new ForbiddenException('Authentification requise');
    }

    // Vérifier l'abonnement SaaS — injectez votre SaasService ici
    // Exemple : const sub = await this.saasService.getSubscription(user.sub);
    // if (!sub || sub.plan === 'sandbox_only') throw new ForbiddenException('Abonnement Pro requis');

    // Pour l'instant, on laisse passer si l'utilisateur est authentifié.
    // TODO: injecter SaasService et vérifier sub.plan !== 'sandbox_only'
    return true;
  }
}
`;
}

function generateNuxtGuard(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// Middleware Nuxt 3 — Vérification abonnement SaaS
// Placer dans : middleware/saas-subscription.ts (ou server/middleware/ pour SSR)
export default defineNuxtRouteMiddleware(async (to) => {
  const protectedPrefixes = ['/dashboard', '/premium', '/profile']
  const isProtected = protectedPrefixes.some((p) => to.path.startsWith(p))
  if (!isProtected) return

  const { loggedIn, user } = useOidcAuth() // Adaptez à votre solution d'auth (Keycloak, nuxt-auth, etc.)
  if (!loggedIn.value) return navigateTo('/login?from=' + to.fullPath)

  // Vérifier l'abonnement via l'API
  try {
    const sub = await $fetch('/api/saas/subscription', {
      headers: useRequestHeaders(['cookie']),
    })
    if (!sub || (sub as any).plan === 'sandbox_only') {
      return navigateTo('/pricing?from=' + to.fullPath)
    }
  } catch {
    return navigateTo('/login')
  }
})
`;
}

function generateNextJsGuard(): string {
  return `// Generated by wallet-cli — ${new Date().toISOString()}
// Middleware NextJS — Vérification abonnement SaaS
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const PROTECTED_PATHS = ['/dashboard', '/api/protected'];

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;
  const isProtected = PROTECTED_PATHS.some((p) => pathname.startsWith(p));

  if (!isProtected) return NextResponse.next();

  // Vérifier le token de session (adaptez à votre auth : NextAuth, Keycloak, JWT cookie...)
  const token = request.cookies.get('auth_token')?.value
    ?? request.headers.get('authorization')?.replace('Bearer ', '');

  if (!token) {
    return NextResponse.redirect(new URL('/login?from=' + pathname, request.url));
  }

  // TODO: décoder le JWT et vérifier l'abonnement
  // const payload = decodeJwt(token);
  // if (!payload.subscription || payload.subscription === 'sandbox_only') {
  //   return NextResponse.redirect(new URL('/pricing', request.url));
  // }

  return NextResponse.next();
}

export const config = {
  matcher: ['/dashboard/:path*', '/api/protected/:path*'],
};
`;
}

function toPascalCase(slug: string): string {
  return slug.split(/[-_]/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

export function registerGenerateCommand(program: Command): void {
  const generate = program.command('generate').description('Générateur de code (Paiements, SaaS, et Widgets)');

  generate
    .command('widget')
    .description('Générer un widget de paiement (Flutter, React, Vue…)')
    .action(async () => {
      console.log(chalk.bold('\n🎨 Générateur de widget de paiement\n'));

      // ── Détection automatique du framework ──
      const detected = detectFramework(process.cwd());
      if (detected !== 'Inconnu') {
        console.log(chalk.dim(`  Projet détecté : ${chalk.green(detected)}\n`));
      }

      const defaultFrameworkIdx = WIDGET_FRAMEWORKS.findIndex((f) => f.value === detected);

      // ── Questions communes ──
      const baseAnswers = await inquirer.prompt([
        {
          type: 'list',
          name: 'framework',
          message: 'Framework cible :',
          choices: WIDGET_FRAMEWORKS,
          default: defaultFrameworkIdx >= 0 ? WIDGET_FRAMEWORKS[defaultFrameworkIdx].value : 'Flutter',
        },
        { type: 'input', name: 'name', message: 'Nom du composant (ex: MyShop) :', validate: (v: string) => v.length > 0 },
        { type: 'input', name: 'projectKey', message: 'Project Key (x-feda-project-key) :' },
      ]);

      // ── Questions spécifiques Flutter ──
      let operators: string[] = ['mtn_open', 'moov'];
      let widgetType = 'bottom-sheet';
      let primaryColor = '#2196F3';

      if (baseAnswers.framework === 'Flutter') {
        const flutterAnswers = await inquirer.prompt([
          {
            type: 'list',
            name: 'type',
            message: 'Type de widget Flutter :',
            choices: [
              { name: '📱 Bottom Sheet de paiement (recommandé)', value: 'bottom-sheet' },
              { name: '🔘 Bouton de paiement inline', value: 'pay-button' },
            ],
          },
          {
            type: 'checkbox',
            name: 'operators',
            message: 'Opérateurs supportés :',
            choices: OPERATORS,
            validate: (v: string[]) => v.length > 0 || 'Sélectionnez au moins un opérateur',
          },
          {
            type: 'input',
            name: 'primaryColor',
            message: 'Couleur principale (hex) :',
            default: '#2196F3',
            validate: (v: string) => /^#[0-9A-Fa-f]{6}$/.test(v) || 'Format hex invalide (ex: #2196F3)',
          },
        ]);
        widgetType = flutterAnswers.type;
        operators = flutterAnswers.operators as string[];
        primaryColor = flutterAnswers.primaryColor as string;
      }

      // ── Questions spécifiques Web (React/Vue) ──
      let cssFramework = 'tailwind';
      if (baseAnswers.framework !== 'Flutter') {
        const webAnswers = await inquirer.prompt([
          {
            type: 'list',
            name: 'cssFramework',
            message: 'Librairie CSS :',
            choices: [
              { name: 'Tailwind CSS', value: 'tailwind' },
              { name: 'CSS Modules', value: 'modules' },
              { name: 'Aucune (styles inline)', value: 'inline' },
            ],
          },
        ]);
        cssFramework = webAnswers.cssFramework;
      }

      // ── Répertoire de sortie ──
      const defaultOutputDir = baseAnswers.framework === 'Flutter' ? 'lib/widgets' : 'src/components';
      const { outputDir } = await inquirer.prompt([
        { type: 'input', name: 'outputDir', message: 'Répertoire de sortie :', default: defaultOutputDir },
      ]);

      const spinner = ora('Génération du widget...').start();

      const fw: string = baseAnswers.framework;
      const isFlutter = fw === 'Flutter';
      const isVue = fw.startsWith('Vue');
      const isReact = fw.startsWith('React');

      // ── Génération du code ──
      let code: string;
      let filename: string;

      if (isFlutter) {
        const baseName = baseAnswers.name.toLowerCase().replace(/\s+/g, '_');
        filename = widgetType === 'bottom-sheet'
          ? `${baseName}_payment_bottom_sheet.dart`
          : `${baseName}_pay_button.dart`;
        code = widgetType === 'bottom-sheet'
          ? generateBottomSheet({ name: baseAnswers.name, projectKey: baseAnswers.projectKey, operators, primaryColor })
          : generatePayButton({ name: baseAnswers.name, projectKey: baseAnswers.projectKey, operators, primaryColor });
      } else if (isVue) {
        filename = `${toPascalCase(baseAnswers.name)}PaymentWidget.vue`;
        code = generateVuePaymentWidget({ name: baseAnswers.name, projectKey: baseAnswers.projectKey, cssFramework });
      } else {
        // React (NextJS ou Vite)
        filename = `${toPascalCase(baseAnswers.name)}PaymentWidget.tsx`;
        code = generateReactPaymentWidget({ name: baseAnswers.name, projectKey: baseAnswers.projectKey, cssFramework });
      }

      const outputPath = path.join(process.cwd(), outputDir as string, filename);
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      fs.writeFileSync(outputPath, code, 'utf8');

      spinner.succeed(`Widget généré !`);
      console.log(`\n  Fichier : ${chalk.cyan(outputPath)}`);

      // ── Instructions d'intégration selon le framework ──
      console.log(chalk.bold('\n📋 Prochaines étapes d\'intégration :'));

      if (isFlutter) {
        console.log(chalk.yellow('\n  1. Ajoutez le SDK à votre pubspec.yaml :'));
        console.log(chalk.cyan('     dependencies:'));
        console.log(chalk.cyan('       feda_flutter: ^0.2.2'));
        console.log(chalk.dim('     (puis lancez : flutter pub get)'));
        console.log(chalk.yellow('\n  2. Initialisez le SDK dans votre main.dart :'));
        console.log(chalk.cyan(`     void main() {`));
        console.log(chalk.cyan(`       FedaFlutter.applyCloudConfig(`));
        console.log(chalk.cyan(`         projectKey: '${baseAnswers.projectKey}',`));
        console.log(chalk.cyan(`         cloudUrl: 'https://VOTRE_INSTANCE_ASH_BWALLET',`));
        console.log(chalk.cyan(`         environment: ApiEnvironment.sandbox,`));
        console.log(chalk.cyan(`       );`));
        console.log(chalk.cyan(`       runApp(const MyApp());`));
        console.log(chalk.cyan(`     }`));
        console.log(chalk.dim(`     Import : import 'package:feda_flutter/feda_flutter.dart';`));
        console.log(chalk.yellow('\n  3. Utilisez le widget dans votre code :'));
        const widgetClass = `${toPascalCase(baseAnswers.name)}${widgetType === 'bottom-sheet' ? 'PaymentBottomSheet' : 'PayButton'}`;
        if (widgetType === 'bottom-sheet') {
          console.log(chalk.cyan(`     ${widgetClass}.show(context, amount: 2500, description: 'Commande #42');`));
        } else {
          console.log(chalk.cyan(`     ${widgetClass}(amount: 2500, description: 'Commande #42', phoneNumber: '+22960000000', operator: 'moov')`));
        }
      } else {
        const pkgInstall = fw.includes('Nuxt') ? 'npm install feda-js' : 'npm install feda-js';
        console.log(chalk.yellow('\n  1. Installez le SDK JS :'));
        console.log(chalk.cyan(`     ${pkgInstall}`));
        console.log(chalk.dim('     (ou configurez le proxy cloud directement via fetch/axios)'));
        console.log(chalk.yellow('\n  2. Configurez les variables d\'environnement :'));
        const envPrefix = fw.includes('Nuxt') ? 'NUXT_PUBLIC' : 'NEXT_PUBLIC';
        console.log(chalk.cyan(`     ${envPrefix}_FEDA_PROJECT_KEY=${baseAnswers.projectKey}`));
        console.log(chalk.cyan(`     ${envPrefix}_FEDA_CLOUD_URL=https://VOTRE_INSTANCE_ASH_BWALLET`));
        console.log(chalk.yellow('\n  3. Importez et utilisez le composant :'));
        if (isVue) {
          console.log(chalk.cyan(`     import ${toPascalCase(baseAnswers.name)}PaymentWidget from '~/components/${filename}';`));
        } else {
          console.log(chalk.cyan(`     import { ${toPascalCase(baseAnswers.name)}PaymentWidget } from './components/${filename}';`));
          console.log(chalk.cyan(`     <${toPascalCase(baseAnswers.name)}PaymentWidget amount={2500} description="Commande #42" />`));
        }
      }
    });

  generate
    .command('pricing-page')
    .description('Générer une page de Tarifs SaaS (Pricing Page) connectée à votre configuration')
    .action(async () => {
      console.log(chalk.bold('\n🛒 Générateur de Pricing Page SaaS\n'));

      const detected = detectFramework(process.cwd());
      const detectedLabel = detected === 'Flutter' ? 'Flutter'
        : detected.includes('Nuxt') ? 'Nuxt (Vue)'
        : detected.includes('NextJS') ? 'NextJS (React)'
        : detected.includes('Vite') && detected.includes('Vue') ? 'Vue (Vite)'
        : detected.includes('Vite') ? 'React (Vite)'
        : null;
      if (detectedLabel) console.log(chalk.dim(`  Projet détecté : ${chalk.green(detected)}\n`));

      const answers = await inquirer.prompt([
        {
          type: 'list',
          name: 'framework',
          message: 'Framework cible :',
          choices: ['Flutter', 'NextJS (React)', 'React (Vite)', 'Nuxt (Vue)', 'Vue (Vite)', 'Laravel'],
          default: detectedLabel ?? 'Flutter',
        },
        { type: 'input', name: 'outputDir', message: 'Répertoire de sortie :', default: './components' },
      ]);
      const spinner = ora('Génération de la page de tarifs...').start();

      const isVue = answers.framework.includes('Vue') || answers.framework.includes('Nuxt');
      const isReact = answers.framework.includes('React') || answers.framework.includes('NextJS');
      const filename = answers.framework === 'Flutter' ? 'pricing_page.dart'
        : isVue ? 'PricingPage.vue'
        : answers.framework === 'Laravel' ? 'pricing-page.blade.php'
        : 'PricingPage.tsx';

      let pricingCode: string;
      if (answers.framework === 'Flutter') {
        pricingCode = generateFlutterPricingPage();
      } else if (isVue) {
        pricingCode = generateNuxtPricingPage();
      } else if (isReact) {
        pricingCode = generateNextPricingPage();
      } else {
        pricingCode = `{{-- Generated by wallet-cli --}}\n{{-- Laravel Pricing Page --}}\n<section class="pricing">\n  <h2>Nos offres</h2>\n  {{-- TODO: loop sur $plans depuis votre controller --}}\n</section>\n`;
      }

      const outputPath = path.join(process.cwd(), answers.outputDir, filename);
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      fs.writeFileSync(outputPath, pricingCode, 'utf8');

      spinner.succeed(`Pricing Page générée pour ${answers.framework} !`);
      console.log(`\n  Fichier : ${chalk.cyan(outputPath)}`);
      console.log(chalk.dim('  Le code récupère dynamiquement vos plans via GET /billing/plans.'));
    });

  generate
    .command('customer-portal')
    .description('Générer un Portail Client SaaS (Customer Portal)')
    .action(async () => {
      console.log(chalk.bold('\n👤 Générateur de Customer Portal SaaS\n'));

      const detected = detectFramework(process.cwd());
      const detectedLabel = detected === 'Flutter' ? 'Flutter'
        : detected.includes('Nuxt') ? 'Nuxt (Vue)'
        : detected.includes('NextJS') ? 'NextJS (React)'
        : detected.includes('Vite') && detected.includes('Vue') ? 'Vue (Vite)'
        : detected.includes('Vite') ? 'React (Vite)'
        : null;
      if (detectedLabel) console.log(chalk.dim(`  Projet détecté : ${chalk.green(detected)}\n`));

      const answers = await inquirer.prompt([
        {
          type: 'list',
          name: 'framework',
          message: 'Framework cible :',
          choices: ['Flutter', 'NextJS (React)', 'React (Vite)', 'Nuxt (Vue)', 'Vue (Vite)', 'Laravel'],
          default: detectedLabel ?? 'Flutter',
        },
        { type: 'input', name: 'outputDir', message: 'Répertoire de sortie :', default: './components' },
      ]);
      const spinner = ora('Génération du portail client...').start();

      const isVue = answers.framework.includes('Vue') || answers.framework.includes('Nuxt');
      const isReact = answers.framework.includes('React') || answers.framework.includes('NextJS');

      let portalCode: string;
      if (answers.framework === 'Flutter') {
        portalCode = generateFlutterCustomerPortal();
      } else if (isVue) {
        portalCode = generateNuxtCustomerPortal();
      } else if (isReact) {
        portalCode = generateNextCustomerPortal();
      } else {
        portalCode = `{{-- Generated by wallet-cli --}}\n{{-- Laravel Customer Portal --}}\n<div class="portal">\n  {{-- TODO: afficher les abonnements de l'utilisateur --}}\n</div>\n`;
      }

      const filename = answers.framework === 'Flutter' ? 'customer_portal.dart'
        : isVue ? 'CustomerPortal.vue'
        : answers.framework === 'Laravel' ? 'customer-portal.blade.php'
        : 'CustomerPortal.tsx';

      const outputPath = path.join(process.cwd(), answers.outputDir, filename);
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      fs.writeFileSync(outputPath, portalCode, 'utf8');

      spinner.succeed(`Customer Portal généré pour ${answers.framework} !`);
      console.log(`\n  Fichier : ${chalk.cyan(outputPath)}`);
    });

  generate
    .command('guard')
    .description('Générer un Guard / Middleware de protection SaaS')
    .action(async () => {
      console.log(chalk.bold('\n🛡️ Générateur de protection SaaS (Guard/Middleware)\n'));

      const detected = detectFramework(process.cwd());
      const detectedGuard = detected === 'Flutter' ? 'Flutter (GoRouter)'
        : detected.includes('NextJS') || (detected.includes('React') && detected.includes('Vite')) ? 'NextJS (Middleware)'
        : null;
      if (detectedGuard) console.log(chalk.dim(`  Projet détecté : ${chalk.green(detected)}\n`));

      const answers = await inquirer.prompt([
        {
          type: 'list',
          name: 'framework',
          message: 'Framework cible :',
          choices: ['Flutter (GoRouter)', 'NestJS', 'NextJS (Middleware)', 'Nuxt (middleware)', 'Laravel'],
          default: detectedGuard ?? 'Flutter (GoRouter)',
        },
        { type: 'input', name: 'outputDir', message: 'Répertoire de sortie :', default: './guards' },
      ]);
      const spinner = ora('Génération du système de protection...').start();

      const filename = answers.framework.includes('Flutter') ? 'saas_guard.dart'
        : answers.framework.includes('NestJS') ? 'saas.guard.ts'
        : answers.framework.includes('Laravel') ? 'SaasMiddleware.php'
        : answers.framework.includes('Nuxt') ? 'saas.middleware.ts'
        : 'middleware.ts';

      const outputPath = path.join(process.cwd(), answers.outputDir, filename);
      let guardCode: string;
      if (answers.framework.includes('Flutter')) {
        guardCode = generateFlutterGuard();
      } else if (answers.framework.includes('NestJS')) {
        guardCode = generateNestJsGuard();
      } else if (answers.framework.includes('Laravel')) {
        guardCode = `<?php\n// Generated by wallet-cli\nnamespace App\\Http\\Middleware;\nuse Closure;\nuse Illuminate\\Http\\Request;\n\nclass SaasSubscriptionMiddleware\n{\n    public function handle(Request $request, Closure $next)\n    {\n        $user = $request->user();\n        if (!$user || !$user->hasActiveSubscription()) {\n            return response()->json(['error' => 'Subscription required'], 403);\n        }\n        return $next($request);\n    }\n}\n`;
      } else if (answers.framework.includes('Nuxt')) {
        guardCode = generateNuxtGuard();
      } else {
        guardCode = generateNextJsGuard();
      }
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      fs.writeFileSync(outputPath, guardCode, 'utf8');

      spinner.succeed(`Guard SaaS généré pour ${answers.framework} !`);
      console.log(`\n  Fichier : ${chalk.cyan(outputPath)}`);
    });
}
